name = "HTML_Entities"
uuid = "7693890a-d069-55fe-a829-b4a6d304f0ee"
keywords = ["Entities", "HTML"]
license = "MIT"
desc = "Entities from HTML data tables"
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
version = "1.0.3"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"
StrTables = "9700d1a9-a7c8-5760-9816-a99fda30bb8f"

[compat]
Artifacts = "1"
RelocatableFolders = "1"
StrTables = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
